package enums;

public enum VoiceExceptionType {
        REQUEST_COUNT_EXCEEDED, REQUEST_TO_LARGE, LANGUAGE_NOT_SUPPORTED, LANGUAGE_NOT_SPECIFIED, TEXT_NOT_SPECIFIED,
    API_KEY_NOT_AVAILABLE, API_KEY_NOT_DEFINED, SSML_NOT_SUPPORTED, IO, UNKNOWN, ILLEGAL_CHAR
}
