package com.github.orthae.discordtriggerstuff.enums;

public enum AudioExceptionType {
    UNSUPPORTED_DISCORD_FILE, DISCORD_NOT_CONNECTED, UNSUPPORTED_AUDIO_FILE, UNKNOWN, IO_DISCORD, UNSPECIFIED_AUDIO_FILE, UNAVAILABLE_AUDIO_FILE, CORRUPTED_AUDIO_FILE;
}
